site_name: Genesis Customizer Docs
site_description: 'Genesis Customizer theme documentation'
site_author: 'SEO Themes'
site_url: 'https://genesiscustomizer.com/'
theme:
  name: 'material'
  favicon: 'library_books'
  logo:
    icon: 'library_books'
  palette:
    primary: 'blue'
    accent: 'indigo'
  feature:
    tabs: false
  font:
    text: 'Nunito Sans'
    code: 'Ubuntu Mono'
copyright: 'Copyright &copy; 2019 <a href="https://seothemes.com/">SEO Themes</a>. All rights reserved.'
repo_name: 'seothemes/genesis-customizer'
repo_url: 'https://github.com/seothemes/genesis-customizer'
extra_css:
- 'stylesheets/extra.css'
extra:
  social:
  - type: 'github'
    link: 'https://github.com/seothemes'
  - type: 'twitter'
    link: 'https://twitter.com/seothemeswp'
  - type: 'facebook'
    link: 'https://facebook.com/genesiscustomizer'
  - type: 'slack'
    link: 'https://slack.com/genesiscustomizer'
markdown_extensions:
- admonition
- codehilite
- pymdownx.arithmatex
- pymdownx.betterem
- pymdownx.caret
- pymdownx.critic
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_svg
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist
- pymdownx.tilde
- toc


pages:
- Getting Started:
  - Pro Modules: getting-started/genesis-customizer-pro-modules.md
  - Importing Demo: getting-started/importing-theme-demo-content.md
  - Child Themes: getting-started/installing-the-genesis-customizer-child-theme.md
  - Minimum Requirements: getting-started/meeting-the-minimum-requirements.md
- Base Styles:
  - Global: base-styles/global.md
  - Body: base-styles/body.md
  - Headings: base-styles/headings.md
  - Buttons: base-styles/buttons.md
  - Links: base-styles/links.md
  - Inputs: base-styles/inputs.md
  - Lists: base-styles/lists.md
  - Blockquotes: base-styles/blockquotes.md
- Header:
  - Primary Header: header/primary-header.md
  - Title Area: header/title-area.md
  - Header Right: header/header-right.md
  - Above Header (Pro): header/above-header-pro.md
  - Header Left (Pro): header/header-left-pro.md
  - Below Header (Pro): header/below-header-pro.md
  - Sticky Header (Pro): header/sticky-header-pro.md
  - Transparent Header (Pro): header/transparent-header-pro.md
  - Header Search (Pro): header/header-search-pro.md
- Menus:
  - Footer Menu: menus/footer-menu.md
  - Menu Toggle: menus/menu-toggle.md
  - Secondary Menu: menus/secondary-menu.md
  - Footer Widgets Menu: menus/footer-widgets-menu.md
  - Mobile Menu: menus/mobile-menu.md
  - Sub Menu Toggle: menus/sub-menu-toggle.md
  - Mega Menu-pro: menus/mega-menu-pro.md
  - Primary Menu: menus/primary-menu.md
  - Sub Menu: menus/sub-menu.md
- Blog Archive:
  - Archive Description: blog-archive/archive-description.md
  - Pagination: blog-archive/pagination.md
  - Settings: blog-archive/settings.md
  - Post Info: blog-archive/post-info.md
  - Entries: blog-archive/entries.md
  - Read More: blog-archive/read-more.md
  - Blog Layouts (Pro): blog-archive/blog-layouts-pro.md
- Content Area:
  - Main Content: content-area/main-content.md
  - Avatar: content-area/avatar.md
  - Breadcrumbs: content-area/breadcrumbs.md
  - Author Box: content-area/author-box.md
  - Above Content (Pro): content-area/above-content-pro.md
  - Below Content (Pro): content-area/below-content-pro.md
- Custom Code:
  - Code: custom-code/code.md
  - Custom CSS (Pro): custom-code/custom-css-pro.md
  - Custom JS (Pro): custom-code/custom-js-pro.md
- Footer:
  - Footer Credits: footer/footer-credits.md
  - Footer Widgets: footer/footer-widgets.md
  - Site Footer: footer/site-footer.md
  - Above Footer (Pro): footer/above-footer-pro.md
  - Below Footer (Pro): footer/below-footer-pro.md
  - Scroll To Top (Pro): footer/scroll-to-top-pro.md
- Hero Section:
  - Settings (Pro): hero-section/settings-pro.md
  - Default Background (Pro): hero-section/default-background-pro.md
- Sidebars:
  - Featured Content: sidebars/featured-content.md
  - Primary Sidebar: sidebars/primary-sidebar.md
  - Secondary Sidebar: sidebars/secondary-sidebar.md
- Single Post Page:
  - After Entry: single-post-page/after-entry.md
  - Entry: single-post-page/entry.md
  - Post Meta: single-post-page/post-meta.md
  - Comments: single-post-page/comments.md
  - Featured Image: single-post-page/featured-image.md
- General:
  - License Key: general/activating-your-pro-license-key.md
  - Site Title: general/changing-the-site-title-and-site-description.md
  - Color Settings: general/color-setting-is-not-clearing-the-value.md
  - Adobe Fonts: general/how-to-add-adobe-fonts-typekit.md
  - Theme Support: general/how-to-add-theme-support-for-genesis-customizer.md
  - Navigation Menu: general/how-to-create-a-navigation-menu.md
  - Install Genesis: general/how-to-install-the-genesis-framework-parent-theme.md
  - Header Flash: general/how-to-prevent-transparent-header-flash-on-load.md
  - Upgrading: general/how-to-upgrade-to-genesis-customizer-pro.md
  - Custom Logo: general/how-to-upload-a-custom-logo.md
  - Colors Not Showing: general/why-are-my-colors-not-showing.md

